name: 🐞 Bug report
description: Report an issue with SlickGrid
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a way to reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) would be nice unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true
  - type: dropdown
    id: framework-used
    attributes:
      label: Which Framework are you using?
      description: Select which framework is use (helps with identifying & replicating the problem)
      options:
        - Angular
        - Aurelia
        - React
        - Vue
        - Vanilla / Plain JS
        - Other
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Environment Info
      description: output of `npx envinfo --system --npmPackages 'SlickGrid' --binaries --browsers`
      render: shell
      placeholder: |
        Framework used (x.y)
        SlickGrid (x.y)
        TypeScript (x.y)
        Browser(s)
        System OS
      value: |
        | Executable          | Version |
        | ------------------- | ------- |
        | (framework used)    | VERSION |
        | SlickGrid | VERSION |
        | TypeScript          | VERSION |
        | Browser(s)          | VERSION |
        | System OS           | VERSION |
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/6pac/SlickGrid/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Wikis](https://github.com/6pac/SlickGrid/wiki).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/6pac/SlickGrid/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/6pac/SlickGrid/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
