name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Install npm dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          browser: chrome