name: With server
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NPM install
        uses: bahmutov/npm-install@v1
      - name: Start Http Server on port 8080
        run: npm start
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:           
          # Run Cypress CI E2E tests in command line
          start: npm run cypress:ci